name: PttMessengerAll
description: PttMessenger PoC Versiyon. Butun Modulleri Barindirir.
version: 1.78
maintainer: Mehmet KAPLAN
license: "Ptt Teknoloji"
projectURL: "https://pttteknoloji.com.tr"
category: PttMessenger