ptt:
    container_name: ptt
    image: pttmessenger/pttmessengerserver:10-mehmet
    restart: always
    volumes:
      - ${PTTMESSENGER_CONFIG_PATH}:/zebra/config
      - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/pttmessenger.yml
      - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/config/pttmessenger.yml
      - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/zebra/config/pttmessenger.yml
      - ${PTTMESSENGER_CERT_PATH}:/zebra/config/cert
      - ${PTTMESSENGER_CERT_PATH}/keystore:/keystore
      - ${PTTMESSENGER_CERT_PATH}/certificates.p12:/certificates.p12
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
