ptt:
    container_name: ptt
    image: pttmessenger/pttmessengerserver:10-mehmet
    restart: always
    volumes:
      - ${PTTMESSENGER_CONFIG_PATH}:/config
      - ${PTTMESSENGER_CERT_PATH}:/config/cert
      - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/pttmessenger.yml
      - ${PTTMESSENGER_CERT_PATH}/keystore:/keystore
      - ${PTTMESSENGER_CERT_PATH}/certificates.p12:/certificates.p12
    tty: true
    stdin_open: true
