.catalog:
  name: "PttMessenger Core Module"
  version: "1.78"
  description: "PttMessenger Core Module for single host"
  questions:
    - variable: PTTMESSENGER_CONFIG_PATH
      description: "PttMessenger Config Directory Path"
      label: "Config Directory Path"
      type: "string"
      required: true
      default: "/opt/PttMessengerServer/config"
    - variable: PTTMESSENGER_CERT_PATH
      description: "PttMessenger Certificate Path"
      label: "Certificate Directory Path"
      type: "string"
      required: true
      default: "/opt/PttCerts/messenger"
ptt:
  scale: 2
