pttrelay:
    container_name: ptt_relay
    image: pttmessenger/pttrelay
    restart: always
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    ports:
     - "${PTT_RELAY_PORT}:443"