redis:
    container_name: redis
    image: pttmessenger/pttredis
    restart: always
    volumes:
      - ${PTT_REDIS_DATA}:/data
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"
