accountpostgres:
    container_name: accountpostgres
    image: pttmessenger/pttpostgres
    restart: always
    volumes:
      - ${PTT_POSTGRES_ACC_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PTT_POSTGRES_ACC_USER}
      POSTGRES_PASSWORD: ${PTT_POSTGRES_ACC_PASSWORD}
      POSTGRES_DB: ${PTT_POSTGRES_ACC_DB}
    tty: true
    stdin_open: true
    ports:
      - "5472:5432"
      