name: PttMessengerMsgPostgres
description: PttMessenger MessageDB PostgreSQL database.
version: 9.5
maintainer: Mehmet KAPLAN
license: "Ptt Teknoloji"
projectURL: "https://pttteknoloji.com.tr"
category: PttMessenger