version: '2'
services:
  PttCoreLB:
      container_name: pttlb
      ports:
        - 443
        - 80
      image: rancher/lb-service-haproxy

  ptt:
      container_name: ptt
      image: pttmessenger/pttmessengerserver:10-mehmet
      restart: always
      volumes:
        - ${PTTMESSENGER_CONFIG_PATH}:/zebra/config
        - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/pttmessenger.yml
        - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/config/pttmessenger.yml
        - ${PTTMESSENGER_CONFIG_PATH}/pttmessenger.yml:/zebra/config/pttmessenger.yml
        - ${PTTMESSENGER_CERT_PATH}:/zebra/config/cert
        - ${PTTMESSENGER_CERT_PATH}/keystore:/keystore
        - ${PTTMESSENGER_CERT_PATH}/certificates.p12:/certificates.p12
      labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
        tty: true
      stdin_open: true
      
  redis:
      container_name: redis
      image: pttmessenger/pttredis
      restart: always
      volumes:
        - ${PTT_REDIS_DATA}:/data
      labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
      tty: true
      stdin_open: true
      
  accountpostgres:
      container_name: accountpostgres
      image: pttmessenger/pttpostgres
      restart: always
      volumes:
        - ${PTT_POSTGRES_ACC_DATA}:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${PTT_POSTGRES_ACC_USER}
        POSTGRES_PASSWORD: ${PTT_POSTGRES_ACC_PASSWORD}
        POSTGRES_DB: ${PTT_POSTGRES_ACC_DB}
      labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
      tty: true
      stdin_open: true

  messagepostgres:
      container_name: messagepostgres
      image: pttmessenger/pttpostgres
      restart: always
      volumes:
        - ${PTT_POSTGRES_MSG_DATA}:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${PTT_POSTGRES_MSG_USER}
        POSTGRES_PASSWORD: ${PTT_POSTGRES_MSG_PASSWORD}
        POSTGRES_DB: ${PTT_POSTGRES_MSG_DB}
      labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
      tty: true
      stdin_open: true
