pttattachment:
    container_name: ptt_attachment
    image: pttmessenger/pttattachment
    restart: always
    volumes:
      - ${PTTATTACH_DATA_PATH}:/export
      - ${PTTATTACH_CONFIG_PATH}:/root/.minio
      - ${PTTATTACH_CERT_PATH}:/root/.minio/certs
    command: server /export 
    tty: true
    stdin_open: true
