name: PttMessengerAttach
description: PttMessenger Attachment Server.
version: 1.0
maintainer: Mehmet KAPLAN
license: "Ptt Teknoloji"
projectURL: "https://pttteknoloji.com.tr"
category: PttMessenger