messagepostgres:
    container_name: messagepostgres
    image: pttmessenger/pttpostgres
    restart: always
    volumes:
      - ${PTT_POSTGRES_MSG_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PTT_POSTGRES_MSG_USER}
      POSTGRES_PASSWORD: ${PTT_POSTGRES_MSG_PASSWORD}
      POSTGRES_DB: ${PTT_POSTGRES_MSG_DB}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    ports:
      - "5462:5432"
