name: PttMessengerCore
description: PttMessenger Core Versiyon. Sadece Core Docker Image Barindirir.
version: 1.78
maintainer: Mehmet KAPLAN
license: "Ptt Teknoloji"
projectURL: "https://pttteknoloji.com.tr"
category: PttMessenger